app = "gvses-mcp-sse-server"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
  # Force single instance deployment for Agent Builder testing
  # Eliminates load balancer routing issues
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  # Keep session affinity but with higher limits for single instance
  session_affinity = "cookie"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "3001"
  NODE_ENV = "production"

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"