name: Deploy to Fly.io Production

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [closed]
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message'
        required: false
        default: 'Manual deployment'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: gvses-market-insights

jobs:
  # Run tests before deployment
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run backend tests
        run: |
          cd backend
          python -m pytest tests/ -v --tb=short || echo "Tests not found or failed - continuing"
        continue-on-error: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --passWithNoTests || echo "No tests found - continuing"
        continue-on-error: true

  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit info
        id: commit
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=%B | head -1)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          echo "🚀 Deploying to production..."
          echo "Commit: ${{ steps.commit.outputs.sha }}"
          echo "Message: ${{ steps.commit.outputs.message }}"
          echo "Author: ${{ steps.commit.outputs.author }}"
          
          flyctl deploy \
            --app ${{ env.APP_NAME }} \
            --ha=false \
            --remote-only \
            --strategy rolling
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Check deployment status
        id: status
        run: |
          flyctl status --app ${{ env.APP_NAME }}
          VERSION=$(flyctl releases --app ${{ env.APP_NAME }} -j | jq -r '.[0].version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify health endpoint
        run: |
          echo "⏳ Waiting for app to be healthy..."
          for i in {1..6}; do
            if curl -f https://${{ env.APP_NAME }}.fly.dev/health; then
              echo "✅ App is healthy!"
              break
            fi
            echo "Attempt $i/6 failed, waiting 10 seconds..."
            sleep 10
          done
          
          # Final check
          curl -f https://${{ env.APP_NAME }}.fly.dev/health || exit 1

      - name: Run smoke tests
        run: |
          echo "🔍 Running smoke tests..."
          
          # Test stock price endpoint
          echo "Testing stock price endpoint..."
          curl -f -s "https://${{ env.APP_NAME }}.fly.dev/api/stock-price?symbol=TSLA" || echo "Stock price endpoint not ready"
          
          # Test agent orchestrator
          echo "Testing agent orchestrator..."
          curl -f -s -X POST "https://${{ env.APP_NAME }}.fly.dev/api/agent/orchestrate" \
            -H "Content-Type: application/json" \
            -d '{"query":"test"}' || echo "Agent orchestrator not ready"
          
          echo "✅ Smoke tests complete"
        continue-on-error: true

      - name: Create deployment summary
        if: always()
        run: |
          cat << EOF > deployment-summary.md
          # Deployment Summary
          
          **Status**: ${{ job.status == 'success' && '✅ Success' || '❌ Failed' }}
          **Version**: v${{ steps.status.outputs.version }}
          **Timestamp**: ${{ steps.commit.outputs.timestamp }}
          
          ## Deployment Details
          - **App**: ${{ env.APP_NAME }}
          - **URL**: https://${{ env.APP_NAME }}.fly.dev
          - **Commit**: ${{ steps.commit.outputs.sha }}
          - **Message**: ${{ steps.commit.outputs.message }}
          - **Author**: ${{ steps.commit.outputs.author }}
          - **Triggered by**: ${{ github.event_name }}
          
          ## Next Steps
          - Monitor app: https://fly.io/apps/${{ env.APP_NAME }}/monitoring
          - View logs: \`fly logs --app ${{ env.APP_NAME }}\`
          - Check status: \`fly status --app ${{ env.APP_NAME }}\`
          EOF
          
          cat deployment-summary.md

      - name: Upload deployment summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployment-summary
          path: deployment-summary.md

      - name: Post deployment notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
            echo "🚀 App URL: https://${{ env.APP_NAME }}.fly.dev"
            echo "📊 Version: v${{ steps.status.outputs.version }}"
            echo "🔍 Monitor: https://fly.io/apps/${{ env.APP_NAME }}/monitoring"
          else
            echo "❌ Deployment failed!"
            echo "📝 Check logs: fly logs --app ${{ env.APP_NAME }}"
            echo "🔍 Debug: fly status --app ${{ env.APP_NAME }}"
          fi